name: Deploy to Amazon Lightsail

on:
  push:
    branches: [ "master" ] 

env:
  AWS_REGION: ap-northeast-2                   # set this to your preferred AWS region, e.g. us-west-1


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Main Branch
      uses: actions/checkout@v3
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.8.1
      with:
        node-version: 16
        
    - name: Install Dependencies
      run: yarn install

    - name: Build Files
      run: yarn run build
      env:
        VITE_MODE: "development" 

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    
    - run: cd build
    
    - name: Transfer Deploy Script use SCP ecosystem
      uses: appleboy/scp-action@master
      with:
        username: bitnami
        host: ${{ secrets.LIGHTSAIL_HOST }}
        key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
        source: "./*"
        target: "/opt/bitnami/apache/htdocs/*"
